const en_US = {
    'intl.hello': "hello",
    'intl.name': 'my name is {name}',
    "intl-Nav-Home": "Home",
    "intl-Nav-Center": "Innovation Center",
    "intl-Nav-Activities": "Activities",
    "intl-Nav-News": "News",
    "intl-Nav-AboutUs": "About Us",
    "intl-Nav-Login": "Login",
    "intl-Nav-Register": "Register",
    "intl-Menu-Email": "Email",
    "intl-Menu-Phone": "Phone",
    "intl-Menu-Hours": "Hours",
    "intl-Home-AboutUs": "About Us",
    "intl-Home-Character": "Alienum phaedrum torquatos nec eu, vis detraxit periculis ex, nihil expetendis in mei.\n" +
    "                            Mei an pericula euripidis, hinc partem ei est. Eos ei nisl graecis, vix aperiri\n" +
    "                            consequat an. Eius lorem tincidunt vix at, vel pertinax sensibus id,\n" +
    "                            error epicurei mea et. Mea facilisis urbanitas moderatius id. Vis ei rationibus\n" +
    "                            definiebas, eu qui purto zril laoreet. Ex error omnium interpretaris pro, alia illum\n" +
    "                            eavim.",
    "intl-Home-JOINLENOVO": "MORE",
    "intl-Home-Sun": "Sun",
    "intl-Home-Mon": "Mon",
    "intl-Home-Tue": "Tue",
    "intl-Home-Wed": "Wed",
    "intl-Home-Thu": "Thu",
    "intl-Home-Fir": "Fir",
    "intl-Home-Sat": "Sat",
    "intl-Home-Mayapply": "May apply",
    "intl-Home-Application": "Application is full",
    "intl-Home-ACITIVITES": "ACITIVITES",
    "intl-Home-Ipsum": "Ipsum lorem ad sea, in reque bonorum definiebas mei. Ius causae conclusionemque in. Sea ex nemore eirmoddelicatissim.",
    "intl-Home-development": "DEVELOPMENT",
    "intl-Home-CREATING": "CREATING A STRATEGY",
    "intl-Home-REVOLUTION": "REVOLUTION SLIDER",
    "intl-Home-Alienum": "Alienum phaedrum torquatos nec eu, vis detraxit periculis ex, nihil expetendis in mei. Mei an pericula euripidis, hinc partem ei est.",
    "intl-Home-MORE": "MORE",
    "intl-AboutUS-ABOUTSUS ": "ABOUTS US",

    "intl-AboutUS-happened ": "What is happened ?",

    "intl-AboutUS-Paragraph1 ": "After association 30" +
    "After years of development, the company has grown from a Chinese company to a global multinational company, and its business has been transformed from a single business to a diversified business, and at the same time from a global PC" +
    "The industry leader gradually evolves into an industrial builder based on equipment + cloudandinfrastructure + cloud, and provides a wide range of intelligent equipment, services and people around the world with a wide range of intelligent equipment manufacturing, service capabilities and supercomputing power construction capabilities",

    "intl-AboutUS-Paragraph2": "Lenovo innovation demonstration center through > innovation exhibition center through the smart life scene of lenovo products and the use of science and technology, focusing on the future smart home, intelligent work travel, smart and intelligent entertainment content, and through the platform based on Internet and artificial intelligence algorithm, the formation of the technical support of intelligent life as a whole.",

    "intl-AboutUS-Paragraph3": "Display of intelligent industry, through the construction of computing power, big data and algorithm platform, the content of the intelligent manufacturing, intelligent medical, financial intelligence education, intelligence and wisdom city, such as the intelligent energy industry system solutions and technical breakthrough, from all walks of life to systematically display in the development of intelligence industry, lenovo enabler status and leading technology.",
    "intl-AboutUS-Paragraph4": "Lenovo innovation display center can help you >Lenovo innovation display center can help you connect the world's 'imagination', leading you into lenovo's smart future world.",
    "intl-AboutUS-Introduction": "Introduction",
    "intl-AboutUS-Admissions": "Admissions & Hours",
    "intl-AboutUS-Facilities": "Facilities",
    "intl-AboutUS-FAQ": "FAQ",
    "intl-AboutUS-Directions": "Directions",
    "intl-AboutUS-operationGuide": "Lenovo VLEC operation guide",
    "intl-AboutUS-Hours": "Hours",
    "intl-AboutUS-TheTimeThat": "- Monday-Friday: 10a.m. - 6p.m. (Reservations Only)",
    "intl-AboutUS-TheTimeThat1": "- Saturday: 9a.m. - 5p.m. (Last Admission by 4:30p.m.)",
    "intl-AboutUS-Closed": "Closed",
    "intl-AboutUS-ClosedTime": "- Sundays, National Holidays, Other Public Holidays and the last day of every year (12/31)",
    "intl-AboutUS-ClosedTime1": "- ※ Other Public Holidays are limited to Labor Day(May 1st), Children's  Day (May 5th) and alternative holidays.",
    "intl-AboutUS-Museum": "Museum guide",
    "intl-AboutUS-Weekdays": "- Weekdays",
    "intl-AboutUS-Weekdays1": "Reservation required (tour by a museum presenter)",
    "intl-AboutUS-Weekdays2": " ※ All weekday visits must be reserved in advance.",
    "intl-AboutUS-Weekdays3": "※ Guided tours can take up to 20 people per group. (If your group'exceeds 20 people, it will be divided into smaller groups of maximum 20 people.)",
    "intl-AboutUS-Saturdays": "- Saturdays",
    "intl-AboutUS-Saturdays1": "- No reservation required ",
    "intl-AboutUS-Saturdays2": " ※ There is no guided tour on Saturdays",
    "intl-AboutUS-VisitorsGuide": "  Visitor's Guide",
    "intl-AboutUS-VisitorsGuide1": " - Smoking is prohibited throughout the entire museum.",
    "intl-AboutUS-VisitorsGuide2": "  - Visitors under the influence of alcohol may not be admitted.",
    "intl-AboutUS-VisitorsGuide3": "  - Photography is allowed. However, filming is prohibited.",
    "intl-AboutUS- Facilities1": " Facilities",
    "intl-AboutUS- Facilities2": " Lorem ipsum dolor sit amet,adipiscing elit.",
    "intl-AboutUS- Facilities3": "Aenean euismod bibendum laoreet. Proin gravida dolor sit",
    "intl-AboutUS-site": "site：",
    "intl-AboutUS-site1": " ##########",
    "intl-AboutUS-Phone": "Phone : ",
    "intl-AboutUS-Phone1": "12323434546",

    "intl-Activities-NumberOfVisitors": "Customer Information",
    "intl-Activities-NumberOfVisitors2": "Number of visitors",
    "intl-Activities-Datails": "Details",
    "intl-Activities-Confirmation": "Comfirmation",

    "intl-Activities-group": "Please provide us customer information.",
    "intl-Activities-Individual": "*Please fill out the form within",
    "intl-Activities-CustomerInformation": "Customer Information",
    "intl-Activities-VisitingPurpose": "Visiting purpose",
    "intl-Activities-Dateofvisit": "Date of visit",
    "intl-Activities-VisitingTime": "Visiting time",
    "intl-Activities-Subordinate": "Industry",
    "intl-Activities-Note": "Note：(Special requests)",
    "intl-Activities-VisitTheUnit": "Organization",
    "intl-Activities-language": "Visiting language",
    "intl-Activities-language1": "Chinese",
    "intl-Activities-language4": "English",
    "intl-Activities-Next": "Next",
    "intl-Activities-Previous": "Previous",
    "intl-Activities-Submit": "Submit",
    "intl-Activities2-Please": "Please select the number of visitor",
    "intl-Activities2-Guided": "Guided tours are for groups of minimum 1 to maximum 30 people.",
    "intl-Activities2-Number": "Number of visitors",
    "intl-Activities2-Under": "Under 12 years",
    "intl-Activities2-Students": "College Students",
    "intl-Activities2-Elementary": "Elementary school students and younger children must be accompanied by adults.(1 adult is required per 2 children.)",
    "intl-Activities2-Eighteen": " 13 to 18 years",
    "intl-Activities2-Adults": "Adults",
    "intl-Activities2-Total number of visitors ":"Total number of visitors ",
    "intl-Activities2-People":"People",
    "intl-Activities3-details": "Please provide us details",
    "intl-Activities3-Information": "Contact Person's Information",
    "intl-Activities3-name": "Name",
    "intl-Activities3-phone": "Mobile phone",
    "intl-Activities3-E-mail": "E-mail",
    "intl-Activities3-Nationality": "Nationality",
    "intl-Activities3-Occupation": "Occupation",
    "intl-Activities3-China": "China",
    "intl-Activities3-TheBritish": "The British",
    "intl-Activities3-Japan": "Japan",
    "intl-Activities3-TheUnitedStates": "The United States",
    "intl-Activities3-I agree": "I agree",
    "intl-Activities3-I disagree": "I disagree",


    "intl-Activities5-Information": "Please comFirm the Information",
    "intl-Activities5-Contact": "Contact Person's  Information",


    "intl-InnovationCenter-InnovationCenter": "The exhibition hall is introduced",
    "intl-InnovationCenter-Ipsum": "Ipsum lorem ad sea, in reque bonorum definiebas mei. Ius causae conclusionemque in. Sea ex\n" +
    "                            nemore eirmoddelicatissim. Sea ex nemore eirmoddelicatissim.",


};
export default en_US;