const zh_CN = {
    'intl.hello': "你好",
    'intl.name': '我的名字是 {name}',
    "intl-Nav-Home":"主页",
    "intl-Nav-Center":"创新中心",
    "intl-Nav-Activities":"活动",
    "intl-Nav-News":"新闻",
    "intl-Nav-AboutUs":"关于我们",
    "intl-Nav-Login":"登陆",
    "intl-Nav-Register":"注册",
    "intl-Menu-Email":"邮箱",
    "intl-Menu-Phone" :"手机",
    "intl-Menu-Hours" :"时间",


    "intl-Home-AboutUs":"关于我们",
    "intl-Home-Character":"这是一种很好的方法，它可以让你的身体变得更健康。你可以在这里看到我的名字，我的名字是我的名字。这是一种很有价值的东西，它是一种很有价值的东西，它是一种很有价值的东西，它是一种很有价值的东西。这是一种不正常的解释，它是一种艺术，它是一种艺术。",
    "intl-Home-JOINLENOVO":"加入联想",
    "intl-Home-Sun":"日",
    "intl-Home-Mon":"一",
    "intl-Home-Tue":"二",
    "intl-Home-Wed":"三",
    "intl-Home-Thu":"四",
    "intl-Home-Fir":"五",
    "intl-Home-Sat":"六",
    "intl-Home-Mayapply":"可申请",
    "intl-Home-Application":"申请已满",
    "intl-Home-ACITIVITES":"活动",
    "intl-Home-Ipsum":"我在海上，在法定的荣誉中。我的结论是。海洋环境",
    "intl-Home-development":"发展",
    "intl-Home-CREATING":"策略",
    "intl-Home-REVOLUTION":"幻灯片",
    "intl-Home-Alienum":"这是一种很好的方法，它可以让你的身体变得更健康。我是一个有精神的人，我的朋友，我的朋友。",
    "intl-Home-MORE":"更多",



    "intl-AboutUS-ABOUTSUS ":"企业简介",
    "intl-AboutUS-happened ":"是发生什么事了?",
    "intl-AboutUS-Paragraph1 ":"联想经过 30\n" +
    "                                        多年的发展，从一家中国公司成长为一家全球化跨国企业，业务从单一业务转化为多元化业务，同时从全球 PC\n" +
    "                                        产业引领者逐步演变为以“设备+云”和“基础设施+云”的产业构建者，以广泛的智能设备制造、服务能力和超级计算力构建能力，为全球提供广泛的智能化设备、服务和人\n" +
    "                                        工智能时代的核心计算力，成为人工智能时代的赋能者。",

    "intl-AboutUS-Paragraph2":"联想创新展示中心通过> 联想创新展示中心通过“智能生活”场景对联想产品及科技的运用，集中展示未来智能家居、智能工作、智能出行及智能娱乐等方面的内容，并通过基于物联网和人工智能算法平台，形成对整体智能生活方面的技术支撑。",

    "intl-AboutUS-Paragraph3":"在智能行业展示中，通过构建计算力、大数据和算法平台的内容，体现智能制造、智能医疗、智能教育、智能金融以及智慧城市、智能能源等各行业的系统解决方案及各行业的技术突破点，系统性地展示在智能行业的发展中，联想所赋能者的地位和技术领先性",  "intl-AboutUS-Paragraph4":"在智能行业展示中，通过构建计算力、大数据和算法平台的内容，体现智能制造、智能医疗、智能教育、智能金融以及智慧城市、智能能源等各行业的系统解决方案及各行业的技术突破点，系统性地展示在智能行业的发展中，联想所赋能者的地位和技术领先性","intl-AboutUS-operationGuide":"联想VLEC操作指南",
    "intl-AboutUS-Introduction":"公司介绍",
    "intl-AboutUS-Admissions":"参观时间",
    "intl-AboutUS-Facilities":"存包处",
    "intl-AboutUS-FAQ":" 常见问题",
    "intl-AboutUS-Directions":" 导航路线",
    "intl-AboutUS-Hours":"时间",
    "intl-AboutUS-TheTimeThat":"- 周一 -周五: 10a.m. - 6p.m. (可预订)",
    "intl-AboutUS-TheTimeThat1":"- 周六: 9a.m. - 5p.m. (最后一次入场时间为下午4:30 )",
    "intl-AboutUS-Closed":"关闭",
    "intl-AboutUS-ClosedTime":"-星期日、国定假日、其他公众假期及最后一天 '每年(12/31)',",
    "intl-AboutUS-ClosedTime1":"- ※ 其他公共假日以五一劳动节(儿童节)为限'5月5日和其他假期.'",
    "intl-AboutUS-Museum":"移动博物馆导游",
    "intl-AboutUS-Weekdays":"-工作日",
    "intl-AboutUS-Weekdays1":"需要预约(由博物馆主持参观)",
    "intl-AboutUS-Weekdays2":"所有工作日的访客必须提前预订。",
    "intl-AboutUS-Weekdays3":"导游团每组最多可容纳20人。(如果您的团队人数超过20人，则会被分成最多20人的小组。)",
    "intl-AboutUS-Saturdays":"- 每逢星期六",
    "intl-AboutUS-Saturdays1":"-不需要预订 ",
    "intl-AboutUS-Saturdays2":" ※星期六没有导游陪同",
    "intl-AboutUS-VisitorsGuide":"  游客指南",
    "intl-AboutUS-VisitorsGuide1":" --整个博物馆禁止吸烟。",
    "intl-AboutUS-VisitorsGuide2":"  - 受酒精影响的访客不得入内。",
    "intl-AboutUS-VisitorsGuide3":"  -允许拍照。然而，拍摄是被禁止的.",
    "intl-AboutUS- Facilities1":" 存包处",
    "intl-AboutUS- Facilities2":"这是一名精英，他是一名精英，他是一名精英.",
    "intl-AboutUS- Facilities3":"这是一种很好的方法。这是一种很好的方法。",
    "intl-AboutUS-site":"地址：",
    "intl-AboutUS-site1":" ##########",
    "intl-AboutUS-Phone":"电话  ：",
    "intl-AboutUS-Phone1":"12323434546",
    "intl-Activities-NumberOfVisitors":"游客数量",
    "intl-Activities-NumberOfVisitors2":"游客数量",
    "intl-Activities-Datails":"详细一些",
    "intl-Activities-Confirmation":"确认",
    "intl-Activities-group":"请按年龄组别选择参观人数。",
    "intl-Activities-Individual":"*个人预约最多可预约9人",
    "intl-Activities-CustomerInformation":"客户信息",
    "intl-Activities-VisitingPurpose":"来访的目的",
    "intl-Activities-Dateofvisit":"访问日期",
    "intl-Activities-VisitingTime":"来访的时间",
    "intl-Activities-Subordinate":"所属行业",
    "intl-Activities-VisitTheUnit":"访问单元",
    "intl-Activities-language":"来访的语言",
    "intl-Activities-Note":"注意 :  (特殊要求)",
    "intl-Activities-language1":"中文",
    "intl-Activities-language2":"韩语",
    "intl-Activities-language3":"日文",
    "intl-Activities-language4":"英语",
    "intl-Activities-language5":"法语",
    "intl-Activities2-Under":"12岁之前",
    "intl-Activities2-Eighteen":"13岁至18岁",
    "intl-Activities2-Students":"大学生",
    "intl-Activities2-Adults":"成人",
    "intl-Activities2-Elementary":"小学生和幼儿必须由成人陪同。(每2名儿童需要1名成人。)",
    "intl-Activities3-name":"姓名",
    "intl-Activities3-phone":"移动电话",
    "intl-Activities3-E-mail":"邮件",
    "intl-Activities3-Nationality":"国籍",
    "intl-Activities3-Occupation":"职业",
    "intl-Activities3-China":"中国",
    "intl-Activities3-TheBritish":"英国",
    "intl-Activities3-Japan":"日本",
    "intl-Activities3-TheUnitedStates":"美国",





    "intl-InnovationCenter-InnovationCenter":"展厅介绍",
    "intl-InnovationCenter-Ipsum":"我在海上，在法定的荣誉中。我的结论是。海的前女友海洋环境",


};
export default zh_CN;